[theme]
primaryColor="#FF6BD8"
backgroundColor="#18181B"
secondaryBackgroundColor="#0F0F10"
textColor="#E0D6DE"
font="Fira Sans:https://fonts.googleapis.com/css2?family=Fira+Sans&display=swap"
headingFont="Fira Mono:https://fonts.googleapis.com/css2?family=Fira+Mono&display=swap"